title: Yue (Julien) Niu
logo: /assets/img/yellowstone.jpeg
description: My personal site.
minima:
  social_links:
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=J7vQ-QEAAAAJ&hl=en" }
    - { platform: twitter, user_url: "https://twitter.com/YuehNiu" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/yue-niu-a3084216a/" }
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
header_pages:
  - publication.md
  - research.md
  - blog.md
